services:
  - type: web
    name: apt-structural-campus
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app   # <-- change from app:app to wsgi:app
    plan: free
    envVars:
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: ADMIN_USERNAME
        value: ${ADMIN_USERNAME}
      - key: ADMIN_PASSWORD
        value: ${ADMIN_PASSWORD}
      - key: SESSION_COOKIE_SECURE
        value: "False"
      - key: MAIL_USERNAME
        value: ${MAIL_USERNAME}
      - key: MAIL_PASSWORD
        value: ${MAIL_PASSWORD}